### ISSUE TITLE
RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - expected type torch.FloatTensor but got torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by Gooddz1** [ms5898/ECBM6040-Project#6]
Traceback (most recent call last):
  File "/home/gooddz/lanenet_fastscnn/Train.py", line 128, in <module>
    loss.backward()
  File "/home/gooddz/anaconda3/envs/fastscnn_lanenet/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/gooddz/anaconda3/envs/fastscnn_lanenet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 98, in backward
    tensors, grad_tensors, retain_graph, create_graph,allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - expected type torch.FloatTensor but got torch.cuda.FloatTensor

**Comment by Gooddz1** [comment]
Why is this problem

**Comment by Gooddz1** [comment]
The problem has been solved. It's my poor foundation

**Comment by Gooddz1** [comment]
The problem has been solved.

**Comment by Will-jing** [comment]
What did you do to solve this problem?I have met the same error

> The problem has been solved.

What did you do to solve this problem?I have met the same error

**Comment by ChenSunMac** [comment]
You can avoid this error by changing the code in cluster_loss3.py in Lanenet folder.

The author somehow commented the .cuda() (I guess he use CPU to train)
